In [4]:
from keras.preprocessing.text import Tokenizer
sentences=[
"I love dogs", 
"i love cats", 
"you love dogs",
"Do you think my dog is amazing?"]

tk = Tokenizer(num_words=100)

tk.fit_on_texts(sentences)
word_index = tk.word_index
print(word_index)
# {'love': 1, 'i': 2, 'dogs': 3, 'cats': 4, 'you': 5}

sequences = tk.texts_to_sequences(sentences)
print(sequences)
# [[2, 1, 3], [2, 1, 5], [4, 1, 3], [6, 4, 7, 8, 9, 10, 11]]

{'love': 1, 'i': 2, 'dogs': 3, 'you': 4, 'cats': 5, 'do': 6, 'think': 7, 'my': 8, 'dog': 9, 'is': 10, 'amazing': 11}
[[2, 1, 3], [2, 1, 5], [4, 1, 3], [6, 4, 7, 8, 9, 10, 11]]


In [6]:
test_data = [
"i really love dogs",
"dogs love food"]

test_seq = tk.texts_to_sequences(test_data)
print(test_seq)

[[2, 1, 3], [3, 1]]


In [11]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

sentences = ["I love my dog", "I love my cat", "You love my dog!", "Doy you think my dog is amazing?"]

tk = Tokenizer(num_words=100+1, oov_token="<OVV>")
tk.fit_on_texts(sentences)
word_index = tk.word_index

sequences = tk.texts_to_sequences(sentences)
# Adding padding with max length of sequence being 5
padded_sequences_pre = pad_sequences(sequences, maxlen=5, truncating="post")
print(padded_sequences_pre)
# [[ 0  0  0  5  3  2  4]
#  [ 0  0  0  5  3  2  7]
#  [ 0  0  0  6  3  2  4]
#  [ 8  6  9  2  4 10 11]]

[[0 5 3 2 4]
 [0 5 3 2 7]
 [0 6 3 2 4]
 [8 6 9 2 4]]


In [29]:
import numpy as np
arr = np.array([1,2,3,4,5,6])

In [30]:
arr.size

6

In [31]:
arr.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [42]:
x = np.array([[1,2],[3,4]]) 
x

array([[1, 2],
       [3, 4]])

In [59]:
np.expand_dims(x, axis=1)

array([[[1, 2]],

       [[3, 4]]])