In [29]:
import numpy as np
arr = np.array([1,2,3,4,5,6])

In [30]:
arr.size

6

In [31]:
arr.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [42]:
x = np.array([[1,2],[3,4]]) 
x

array([[1, 2],
       [3, 4]])

In [59]:
np.expand_dims(x, axis=1)

array([[[1, 2]],

       [[3, 4]]])